# Generated by Django 5.1.4 on 2024-12-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='tipo_prenda',
            field=models.CharField(choices=[('pantalon', 'Pantalón'), ('camisa', 'Camisa'), ('saco', 'Saco'), ('calcetines', 'Calcetines'), ('zapatos', 'Zapatos'), ('medias', 'Medias'), ('blusa', 'Blusa'), ('chaleco', 'Chaleco'), ('traje', 'Traje'), ('pantalones_jeans', 'Pantalones Jeans'), ('chaquetas', 'Chaquetas'), ('jeans', 'Jeans'), ('jersey', 'Jersey'), ('sweater', 'Sweater'), ('t-shirt', 'T-Shirt'), ('buzo', 'Buzo'), ('sudadera', 'Sudadera'), ('pantalones_shorts', 'Pantalones Shorts')], default='pantalon', max_length=50),
        ),
    ]
